config/routes.rb
Faxriot::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/wxzt', :as => 'rails_admin'

  root :to => 'home#index'
  resources :fax, :only=>[:new,:create], :as=>:faxes
  resources :article, :only=>[:new,:index,:create], :as=>:articles
  get '/faq' => 'faq#index', :as => :faq

  get '/fax/pending/:uniq_id' => 'fax#pending_fax', :as=>:pending_fax
  get '/fax/approve/:uniq_id/:confirm_token' => 'fax#approve_fax', :as=>:approve_fax
  get '/fax/wqerlkjasfd/:uniq_id' => 'fax#cover_page', :as=>:cover_page

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :active, :body, :order, :title
end

app/models/attachment.rb
require 'file_size_validator'

class Attachment < ActiveRecord::Base
  attr_accessible :fax_id, :upload
  belongs_to :fax
  mount_uploader :upload, AttachmentUploader
  validates :upload,
    :file_size => {
      :maximum => 5.megabytes.to_i
    }
  before_create :generate_token

  def base64encoded
    Base64.encode64(open(upload.current_path){ |io| io.read })
  end

  protected

  def generate_token
    self.unique_token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless Attachment.where(unique_token: random_token).exists?
    end
  end

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :order, :question, :active
  validates_presence_of :answer
  validates_presence_of :question

end

app/models/fax.rb
class Fax < ActiveRecord::Base
  include FaxHelper
  apply_simple_captcha
  attr_accessible :cover_text, :from_company, :from_email, :from_name, :to_company, :to_fax, :to_name, :attachments_attributes
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments
  before_create :generate_unique
  before_create :clean_email

  validates_presence_of :from_name
  validates_presence_of :from_email
  validates_presence_of :to_name
  validates :to_fax, :presence => true, :numericality => true
  validates_length_of :to_fax, :is => 10

  private

  def clean_email
    self.sanitized_email= normalize_email(self.from_email)
  end

  def generate_unique
    self.uniq_id = Digest::SHA2.hexdigest(Time.now.to_s + self.from_name + self.from_email)[-10,10]
    self.confirm_token= Digest::SHA2.hexdigest(self.from_name+self.from_email+Time.now.to_s)[-12,12]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SimpleCaptcha::ControllerHelpers
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
    @faqs = Faq.where({:active=>true}).order('"order" asc').all
  end
end

app/controllers/fax_controller.rb
require 'sr_fax_client'

class FaxController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  include FaxHelper

  def cover_page
    @fax = Fax.find_by_uniq_id params[:uniq_id]
    @optional_text = @fax.cover_text || 'None'
    render :layout => false
  end

  def create
    if simple_captcha_valid? or (Rails.env.development? or Rails.env.test?)
      fax = Fax.new(params[:fax])
      # Now log the user info
      fax.remote_addr=request.env['REMOTE_ADDR']
      fax.http_referrer=request.env['HTTP_REFERER']
      fax.http_user_agent=request.env['HTTP_USER_AGENT']
      #check the user hasn't sent more than 3 faxes the last 24 hours
      user_check = Fax.select('sanitized_email').where('created_at > ? AND sanitized_email = ?', Time.now - 24.hours, normalize_email(fax.from_email))
      if user_check.count < 3
        if fax.save
          redirect_to pending_fax_path(:uniq_id => fax.uniq_id)
        else
          # Validation problems tell the user to go back
          flash[:error] = join_errors_html(fax.errors.full_messages) if fax.errors.present?
        end
      else
        flash[:error] = 'You can only submit 3 free faxes in a 24 hour time period. Please try again later.'
        redirect_to root_path
      end
    else
      flash[:error]='Captcha was entered incorrectly.'
      redirect_to root_url
    end
  end

  def pending_fax
    @fax = Fax.find_by_uniq_id(params[:uniq_id])
    raise ActionController::RoutingError.new('Web page not found.') if @fax.blank?
    SRFaxClient.delay.create_fax_cover_sheet(@fax.uniq_id,cover_page_url(:uniq_id => @fax.uniq_id))
  end

  def approve_fax
    if Rails.env.development? and params[:uniq_id] == 'dev'
      @fax = Fax.first || Fax.new
      @fax.from_email='test@test.com'
    else
      @fax = Fax.find_by_uniq_id(params[:uniq_id])
      if @fax.confirm_token == params[:confirm_token] and not @fax.is_confirmed
        @fax.is_confirmed=true
        @fax.save!
        unless Rails.env.test?
          if Rails.env.development?
            SRFaxClient.send_fax(@fax)
          else
            SRFaxClient.delay.send_fax(@fax)
          end
        end
      else
        if @fax.confirm_token != params[:confirm_token]
          redirect_to root_url, :flash =>{ :error => 'The security token in this link is unknown. Make sure you are clicking on the approval link found in your email.'}
        else
          redirect_to root_url, :flash =>{ :error => 'This fax has already been confirmed. Check your email for status.'} if not @fax.is_sent?
          redirect_to root_url, :flash=>{ :error=>'This fax has already been delivered.'} if @fax.is_sent?
        end
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @fax = Fax.new
    3.times { @fax.attachments.build }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/fax_helper.rb
module FaxHelper

  #Sanitize the email address so anything that looks like
  # sam.contapay+100@gmail.com looks like
  # samcontapay@gmail.com
  def normalize_email(email)
    tokens = email.split('@')
    first_part = tokens[0].gsub('.','')

    first_part = first_part[0..first_part.index('+')-1] if first_part.include?'+'
    [first_part,tokens[1]].join('@')
  end

  def join_errors_html errors
    #result = ''
    #errors.each { |msg| result << "<p>#{msg}</p>"}
    test = errors.map {|msg| "<p>#{msg}</p>"}
    test.join('')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/article/index.html.haml
%div.container-narrow

  %div.masthead
    %ul.nav.nav-pills.pull-right
      %li#home= link_to "Home", root_path
      %li#faq= link_to "FAQ", faq_path
      %li#news.active= link_to "News", articles_url
    %h3.muted Fax Riot
    %hr

  %h1 Latest Articles
  %div.span8
    - @articles.each do |article|
      %p
        -if article.active?
          %h2= article.title
          %p= raw(article.body)

app/views/faq/index.html.haml
%div.container-narrow
  %div.masthead
    %ul.nav.nav-pills.pull-right
      -#%li
      -#  %div#fb-like{:width=>30,:height=>30, :style=>'margin-top: 2px; margin-bottom: 2px;margin-right: 4px'}
      -#    %a#facebook-post
      -#      = image_tag "fb_button.png"
      %li#home= link_to "Home", root_path
      %li#faq.active= link_to "FAQ", faq_path
      %li#news= link_to "News", articles_url
    %h3.muted Fax Riot
    %hr

  %div.span8
    - @faqs.each do |faq|
      %p
        %i= faq.question
        %p= raw(faq.answer)

app/views/fax/_fax_form.html.haml
=form_for @fax, :html=>{:multipart=>true, :class=>'fax-form'} do |f|
  %h5.fax-form-heading Please fill out all required information. They are highlighted in red.
  %h4 From
  =f.text_field :from_name, :placeholder=>'Name', :class=>'input-block-level required-input'
  =f.text_field :from_email, :placeholder=>'Email', :class=>'input-block-level required-input'
  %h4 To
  =f.text_field :to_name, :placeholder=>'Name', :class=>'input-block-level required-input'
  - #f.text_field :to_company, :placeholder=>'Company (Optional)', :class=>'input-block-level'
  =f.label :to_fax, 'No dashes or parentheses. US numbers only (i.e. 5555551212)'
  =f.telephone_field :to_fax, :placeholder=>'Fax Number', :class=>'input-block-level required-input'
  %h4 Fax
  =f.text_area :cover_text, :placeholder=>'Optional', :class=>'input-block-level', :rows=>4
  =f.label :attachments, 'Attachments must be less than 5 Megabytes each. Supported file types: jpg,jpeg,png,bmp,tiff,pdf,txt,rtf,doc,docx'
  =f.fields_for :attachments do |a|
    =a.file_field :upload, :class=>'input-block-level'
  %div#captcha_box{:width=>600}= show_simple_captcha
  %p
    =f.submit 'Send Fax', :class=>'btn btn-large btn-primary'

app/views/fax/approve_fax.html.haml
%div.container-narrow

  %div.masthead
    %ul.nav.nav-pills.pull-right
      %li#home= link_to "Home", root_path
      %li#faq= link_to "FAQ", faq_path
    %h3.muted Fax Riot
    %hr

  %div.fax-pending
    %h1 Fax approved
    %p
      Thank you. You have successfully queued your fax for sending. Please give it 5 to 10 minutes. When the fax has
      been successfully sent you will receive a notification email at #{@fax.from_email}. This service is provided free of
      charge make sure you tell your friends.
    %p
      The fax will be sent to this phone number:
    %p
      <i>#{@fax.to_fax}</i>
    %p
      <i>- Fax Riot Team</i>
    %div#social_icons
      %p
        %h5 Share this with your friends
      %div#fb-like{:width=>30,:height=>30, :style=>'margin-top: 2px; margin-bottom: 2px;margin-right: 4px'}
        %a#facebook-post{:style=>'float: left;'}
          = image_tag "fb_button.png"
        %div#twitter_share{:style=>'margin-left:3px; float:left;'}
          <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-url="www.faxriot.com" data-text="I sent a free fax today using http://www.faxriot.com. Send 3 free faxes a day. Free fax service." data-hashtags='faxriot,freefax'>Tweet</a>
    %div{:style=>'height:8px; clear:both;'}

app/views/fax/cover_page.html.haml
!!!html
%head
  :css
    body { font-family: "Arial" }


%body
  %h1 Fax Riot
  %h5 Sent using http://www.faxriot.com - free faxing to any US Based phone number
  %hr
  %p
    To: #{@fax.to_name} <br />
    From: #{@fax.from_name}  <br />
    To Fax Number: #{@fax.to_fax}     <br />
    Number of pages: #{@fax.attachments.count + 1}  <br />
  %hr
  %p
    Comments: #{@optional_text}

  %footer
    Fax riot, http://www.faxriot.com, send faxes for free to any US based phone number

app/views/fax/pending_fax.html.haml
%div.container-narrow

  %div.masthead
    %ul.nav.nav-pills.pull-right
      %li#home= link_to "Home", root_path
      %li#faq= link_to "FAQ", faq_path
    %h3.muted Fax Riot
    %hr

  %div.fax-pending
    %h1 Fax pending please check your email
    %p
      You have successfully created a fax. Please check your email and click on the link
      to confirm that you wish to send this fax. The fax will not be sent unless you click on this link.
      If you used the wrong email please create another fax. We do not change email addresses if entered
      incorrectly.
    %p
      The fax will be sent to this email:
    %p
      Email: <i>#{@fax.from_email}</i>
    %p
      If you do not confirm this within 24 hours your fax will be deleted and you will have to resubmit it.
    %p
      Fax Riot Team

app/views/home/_be_back.html.haml
%div.fax-form
  %h4 Sorry we will be back shortly
  %p
    This service got bigger than there was capacity allocated for it. We are adjusting our servers to handle the massive
    amount of people and faxes being generated. We apologize for the inconvenience and hope to have you able to send faxes again.
    If you have any questions please send them to #{mail_to 'feedback@faxriot.com'}.
  %p
    We appreciate your continued support and patience during this time.
  %p
    %b Fax Riot Team

app/views/home/index.html.haml
%div.container-narrow

  %div.masthead
    %ul.nav.nav-pills.pull-right
      -#%li
      -#  %div#fb-like{:width=>30,:height=>30, :style=>'margin-top: 2px; margin-bottom: 2px;margin-right: 4px'}
      -#    %a#facebook-post{:href=>'#fax-form'}
      -#      = image_tag "fb_button.png"
      %li#home.active= link_to "Home", root_path
      %li#faq= link_to "FAQ", faq_path
      %li#news= link_to "News", articles_url
    %h3.muted Fax Riot
    %hr

  %div.jumbotron
    %h1 Send a Fax - Free!
    %p.lead
      No charge to send a fax. No need to sign up. No credit card required. This service is provided completely free of charge.
      %blockquote "No sign up, no payment required, and we don't spam your email. Just the fax."
    - if ALLOW_FAX
      %a.btn.btn-large.btn-success{:href=>'#fax-form'} Begin
  %div.row-fluid.marketing
    %div.span12{:style=>'text-align:center'}
      No commitment send a fax today. Fax Riot a fast, easy way to send a fax.

  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, raw(msg), :id => "flash_#{name}"

  - if ALLOW_FAX
    %div#fax-form
      = render :partial => 'fax/fax_form'
  - else
    = render :partial => 'be_back'

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title Fax Riot::Send Free Faxes Over the Internet
    = stylesheet_link_tag "application", :media=>"all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name=>'title', :content=>'FaxRiot::Free internet fax service'}
    %meta{:name=>'description', :content=>'Send free faxes over the internet. No payment or sign up necessary. Send up to 3 pages to any number in the US.'}
    %meta{:name=>'keywords', :content=>'fax,internet fax,free fax,pc fax,send fax,send fax from pc,computer fax,fax from computer'}
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">

  %body
    %div#fb-root

  :javascript
    window.fbAsyncInit = function() {
      // init the FB JS SDK
      FB.init({
        appId      : '368901399877903',                        // App ID from the app dashboard
        channelUrl : "#{root_url}channel.html", // Channel file for x-domain comms
        status     : true,                                 // Check Facebook Login status
        xfbml      : true                                  // Look for social plugins on the page
      });

      // Additional initialization code such as adding Event Listeners goes here
    };

    // Load the SDK asynchronously
    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/all.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41322599-1', 'faxriot.com');
    ga('send', 'pageview');

    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");


  = yield

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>